# -*- coding: utf-8 -*-

# Pentagonal numbers are generated by the formula, Pn = n(3n−1)/2. The first ten pentagonal numbers are:

# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj | is minimised
# what is the value of D?

from math import *
from common_functions import timing

def check_pentagonal(num):
    num = 1 + sqrt(1 + (24 * num))
    if (num % 6 == 0):
        return True
    else:
        return False

timer = timing()

for a in range (1, 10000):
    for b in range(2, 10000):
        if b > a:
            j = (3 * a * a - a) * 0.5
            k = (3 * b * b - b) * 0.5
            if check_pentagonal(j + k):
                if check_pentagonal(k - j):
                    break
    else:
        continue
    break

timer("The minimum value of D is {}".format(k-j))
    