# -*- coding: utf-8 -*-

# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#
# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.

from math import *

flag = True
i = 286
while (flag):
    print i
    t = 0.5 * i * (i + 1)
    p = (1 + sqrt(1 + (24 * t))) % 6
    h = (1 + sqrt(1 + (8 * t))) % 4
    if (p == 0) and (h == 0):
        flag = False
        print i, t
    i = i + 1
